### ISSUE TITLE
Invalid chain ID when run artelad start

### ISSUE THREAD

**Issue by fewensa** [artela-network/artela#114]
I'm follow this document https://docs.artela.network/develop/node/run-full-node and when i run arteland start, I got this error, how can I fix this?

```
# /tmp/test/artelad start --log_level=debug
panic: artela: []: invalid chain ID

goroutine 11 [running]:
github.com/artela-network/artela/x/evm/keeper.(*Keeper).WithChainID(0xc00168e600, {0xc00190e758?, 0xc000ceddc0?})
        github.com/artela-network/artela/x/evm/keeper/keeper.go:184 +0xc6
github.com/artela-network/artela/x/evm/keeper.NewKeeper({0x4c4af80?, 0xc0000ab2b0}, {0x4c17e98?, 0xc001996650}, {0x4c17ee8?, 0xc001996680}, {_, _, _}, {0x4c48be0, ...}, ...)
        github.com/artela-network/artela/x/evm/keeper/keeper.go:135 +0x731
github.com/artela-network/artela/app.NewArtela({0x4c381e0, 0xc0000aa820}, {0x4c4cc88, 0xc000014150}, {0x0, 0x0}, 0x1, 0xc00140f440, {0xc000d80d60, 0xe}, ...)
        github.com/artela-network/artela/app/app.go:549 +0x3bee
github.com/artela-network/artela/cmd/artelad/cmd.appCreator.newApp({{{0x4c41db0, 0xc00012d820}, {0x4c590a0, 0xc0000ab2b0}, {0x4c483a0, 0xc000d169c0}, 0xc00048b858}}, {0x4c381e0, 0xc0000aa820}, {0x4c4cc88, ...}, ...)
        github.com/artela-network/artela/cmd/artelad/cmd/root.go:291 +0xa25
github.com/artela-network/artela/ethereum/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x4c57eb0, 0xc00169a3c0}, 0x0, {0xc001694448, 0x6}, {0x4c590a0, ...}, ...}, ...)
        github.com/artela-network/artela/ethereum/server/start.go:334 +0x3ee
github.com/artela-network/artela/ethereum/server.StartCmd.func2.2()
        github.com/artela-network/artela/ethereum/server/start.go:158 +0x58
github.com/artela-network/artela/ethereum/server.wrapCPUProfile.func2()
        github.com/artela-network/artela/ethereum/server/start.go:631 +0x29
created by github.com/artela-network/artela/ethereum/server.wrapCPUProfile
        github.com/artela-network/artela/ethereum/server/start.go:630 +0x24a
```

I'm used prebuilt https://github.com/artela-network/artela/releases/tag/v0.4.7-rc6

**Comment by luketheart** [comment]
Can you check again if you have correctly copied genesis.json into .artelad/config/genesis.json? The second line of ~/.artelad/config/genesis.json should look like the one shown below:
![image](https://github.com/artela-network/artela/assets/129730838/9e3ba286-571a-4b83-82b5-f154ddafd458)

**Comment by fewensa** [comment]
```
{
  "genesis_time": "2024-05-24T12:54:13.16802109Z",
  "chain_id": "artela",
  "initial_height": "1",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1"
    },
....
```

this is my genesis.jso, I'm use this command to genereate it
```
artelad init art0
```

**Comment by fewensa** [comment]
https://asciinema.org/a/az12XamHCMQL8eaNW0kqS6v96

not have this file when initialized.

**Comment by luketheart** [comment]
`curl -o ~/.artelad/config/genesis.json https://docs.artela.network/assets/files/genesis-314f4b0294712c1bc6c3f4213fa76465.json`

**Comment by fewensa** [comment]
It works, Thanks.

**Comment by fewensa** [comment]
Hi @luketheart , there have new issue, Looks like can not sync block?
![image](https://github.com/artela-network/artela/assets/37804932/82b54aab-94c9-40bf-8f84-962c837fba98)

**Comment by luketheart** [comment]
You are not connected to any seed nodes, which might be because the currently configured seed network is too busy to connect. Please join our [Discord](https://discord.com/invite/artela) to find more available seeds.

**Comment by luketheart** [comment]
Close due to in-activity.
