### ISSUE TITLE
A contract that only defines function owner() external returns (address) cannot correctly validate permissions when binding with an aspect.

### ISSUE THREAD

**Issue by lukeweb3** [artela-network/artela#182]
#### System information

Artelad version: `v0.4.9-rc9`
Aspect-libs version: e.g. @artela/aspect-libs@0.0.36
Web3 version: e.g. @artela/web3@1.9.24 
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
Deploy success.

#### Actual behaviour
If a contract only defines function owner() external returns (address), it encounters insufficient permission validation when binding with an aspect. The error message is as follows:
```shell
(node:66710) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/cppppppp/project/github/hyperlanehook/bridgeaspect/node_modules/web3-core-helpers/lib/errors.js:28
        var err = new Error('Returned error: ' + message);
                  ^

Error: Returned error: rpc error: code = Unknown desc = contract ownership validation failed
    at Object.ErrorResponse (/Users/cppppppp/project/github/hyperlanehook/bridgeaspect/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /Users/cppppppp/project/github/hyperlanehook/bridgeaspect/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /Users/cppppppp/project/github/hyperlanehook/bridgeaspect/node_modules/web3-providers-http/lib/index.js:127:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  data: null
}
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by lukeweb3** [comment]
Fixed in: https://github.com/artela-network/aspect-core/pull/69
