### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by dongjl123** [artela-network/artela#185]
#### System information

Artelad version: `v0.4.9-rc9   `
OS & Version: Linux

#### Expected behaviour
Running healthy.

#### Actual behaviour
The node crashes and prints the following logs:
`goroutine 3036652498 [running]:
github.com/artela-network/artela/ethereum/rpc/pubsub.(*memEventBus).Subscribe.func1()
        github.com/artela-network/artela/ethereum/rpc/pubsub/pubsub.go:103 +0xfc
github.com/artela-network/artela/ethereum/rpc/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1(0xc19a79f5c0, 0xc1232eac00)
        github.com/artela-network/artela/ethereum/rpc/filters/api.go:154 +0x671
created by github.com/artela-network/artela/ethereum/rpc/filters.(*PublicFilterAPI).NewPendingTransactionFilter in goroutine 3036652288
        github.com/artela-network/artela/ethereum/rpc/filters/api.go:144 +0x3bf`

#### Steps to reproduce the behaviour
Unknown

When submitting logs: please submit them as text and not screenshots.

**Comment by lukeweb3** [comment]
Not able to reproduce this issue but added a safe close of subscribe chan to avod duplicated close of channel.
